### ISSUE TITLE
 average recognition precision

### ISSUE THREAD

**Issue by ifangcheng** [fucusy/Cross-View-Gait-Based-Human-Identification-with-Deep-CNNs#1]
The  average recognition precision 88.29 is for a 1 vs 1 verification problem or 1 vs N  recognition problem?
Also, the around 90% accuracy on CASIA_B dataset (as illustrated in the paper) is for  a 1 vs 1 verification problem or 1 vs N  recognition problem?
BTW, can the author leave an email so that more details of the paper <A Comprehensive Study on Cross-View Gait Based Human Identification with Deep CNNs> can be discussed with readers and researchers?

**Comment by fucusy** [comment]
The average recognition precision is for recognition problem. I am not the author of the paper. If you have any problem about the code, we can discuss at here.
